import smtplib, ssl
from email.message import EmailMessage
from datetime import datetime
import uuid
import random

def generate_message():
    # Real timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Unique Case ID
    case_id = str(uuid.uuid4())

    # Real HTTP status codes
    status_codes = {
        200: "SUCCESS",
        404: "NOT FOUND",
        500: "SERVER ERROR",
        403: "FORBIDDEN",
        302: "REDIRECTED"
    }

    # Randomly pick one
    code = random.choice(list(status_codes.keys()))
    status = status_codes[code]

    # Build the message
    message = f"""
Demo Alert: This message was generated by Brianas Python project at 2025-09-01 11:15:22. No action required.

"""
    return message
def send_sms_via_verizon(message, phone_number, gmail_addr, gmail_app_password):
    """Send a text to a Verizon number using Gmail SMTP."""
    recipient = f"{phone_number}@vtext.com"  # Verizon SMS gateway

    msg = EmailMessage()
    msg["From"] = gmail_addr
    msg["To"] = recipient
    msg["Subject"] = ""  # SMS ignores subject
    msg.set_content(message)

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(gmail_addr, gmail_app_password)  # <-- this is where server.login comes from
        server.send_message(msg)

if __name__ == "__main__":
    msg = generate_message()
    print(msg)

import os

log_path = os.path.abspath("system_logs.txt")  # full file path
with open(log_path, "a") as f:
    f.write(msg + "\n" + "-"*40 + "\n")

print(f"[LOGGED] Message saved to: {log_path}")


if __name__ == "__main__":
    msg = generate_message()
    print(msg)

    # Save run to a log file
    with open("system_logs.txt", "a") as f:
        f.write(msg + "\n" + "-"*40 + "\n")

    # --- SEND IT AS A TEXT TO YOUR OWN VERIZON NUMBER ---
    # Replace these with your info:
    YOUR_NUMBER = "7322898665"        # e.g. "7322898665"
    GMAIL_ADDR  = "dankanimeallover@gmail.com"
    APP_PASS    = "avpgeekbdwoxroir"   # from Google App Passwords

    # Keep it short for SMS (Verizon truncates long messages)
    sms_msg = msg.strip()[:300]  # trim to ~300 chars to be safe
    send_sms_via_verizon(sms_msg, YOUR_NUMBER, GMAIL_ADDR, APP_PASS)

